update Service account requirements in README
terraform-google-modules/terraform-google-sap pull request #5
Opened 2019-09-03 18:14 UTC by evkuzin

Regarding #4

2019-09-05 15:50 UTC, aaron-lane requested changes
The ask of #4 is to document the required permissions for the service account identity attached to the VM instances. This branch presently changes the required permissions for the service account identity assumed by Terraform.

2019-09-09 15:15 UTC, evkuzin commented
@aaron-lane Recover paragraph about SA used by TF.
add one more paragraph for SA used by VMs

2019-09-10 15:52 UTC, aaron-lane requested changes
Thanks @evkuzin.

This still requires some changes. As mentioned in #4, the incomplete roles lists exist in the READMEs of the submodules, specifically `sap_hana` and `sap_hana_ha`. The details you provided need to be present in those READMEs.

2019-09-10 18:37 UTC, aaron-lane approved these changes

2019-09-10 18:38 UTC, merged